name: ev_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  accordion: ^2.6.0
  animated_notch_bottom_bar: ^1.0.3
  cloud_firestore: ^6.0.1
  dartz: ^0.10.1
  dashed_progress_bar: ^0.0.1
  equatable: ^2.0.7
  firebase_auth: ^6.1.3
  firebase_core: ^4.3.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  font_awesome_icon_class: ^0.0.6
  get: ^4.7.3
  google_sign_in: ^6.2.1
  gradient_progress_bar: ^1.0.7
  model_viewer_plus: ^1.9.3

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/3d_models/
    - assets/images/
